#!/usr/bin/env bash
# Show logs
USE_FZF=${USE_FZF:-"true"}

function _fzf() {
    if [[ $USE_FZF = "true" ]]; then
        exec fzf -0 -1 --no-sort "$@" $filter
    else
        cat
    fi
}

function _cache() {
    HASH=$(echo "$@" | md5 )
    CACHE_FILE="/tmp/${HASH}"
    if [[ ! -e $CACHE_FILE ]] ||  [[ $(($(date +%s)-$(date -r "$CACHE_FILE" +%s))) -ge 3600 ]]; then
        RESULT=$(eval "$@")
        echo "$RESULT" > /tmp/"$HASH"
    fi
    cat "$CACHE_FILE"
}

function get_labels() {
    _cache  'kubectl get pods -o=custom-columns="D:metadata.labels.app\.name" --no-headers | sort | uniq'
}

if [[ $# -eq 0 ]] || [[ $1 = '--'* ]]; then
    # Is it git repo?
    # If yes use repo name as Label
    RESULT=$(basename $(git rev-parse --show-toplevel 2> /dev/null) 2> /dev/null)
    if [[ $? -eq 0 ]]; then
        echo "Got service name from git $RESULT"
        SELECTOR="-l app.name=$RESULT"
        echo "Note: '$SELECTOR' will be using as label"
        echo $CMD
    else
        # Suggest selector if it's not a git repo
        # TODO add cache and check it if name in list
        SERVICE_NAME=$(get_labels | _fzf --prompt="Select app.name label vaule:>")
        SELECTOR="-l app.name=$SERVICE_NAME"
    fi
# Use first argument as label name
elif [[ $# -eq 1 ]];then
    SELECTOR="-l app.name=$1"
    shift
else
    # Gettigng logs from one pod. Pod name is a second argument
    SELECTOR=$2
    shift 2
fi

CMD="stern $SELECTOR ${@:-"--tail 10"}"
echo "Running '$CMD'"
exec $CMD


